declare module "parallax-js"
declare module "vue3typed"
declare module "@ant-design/icon"
declare module '*.svg'
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.bmp'
declare module '*.tiff'